### PR TITLE
fix: lazy sync clears vendor directory on second sync

### LINKED ISSUE #319: issue with lazy sync functionality
Background:

The vendir.yml file contains the configuration lazy: true. Upon running vendir sync on a clean project, the project was updated with the vendor directory and all dependencies, along with the vendir.lock.yaml. However, running vendir sync a second time resulted in the complete clearance of the vendor/ directory.

sample vendir.yml :

```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: dir
    lazy: true
    directory:
      path: ./some-content
```

What I expected:
I expected the vendir sync to skip populating the vendor directory in the second run without clearing the directory.

Environment:

Vendir version: 0.36.0
Operating System: Photon 3/5 or Ubuntu

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by fritzduchardt**
/closes #319

### CODE REVIEW

File: pkg/vendir/directory/directory.go [hunk 1]
```diff
@@ -89,6 +89,11 @@ func (d *Directory) Sync(syncOpts SyncOpts) (ctlconf.LockDirectory, error) {
 		if skipFetching {
```
Comment (prembhaskal) [inline pkg/vendir/directory/directory.go:89]: A thought, Should we rename this variable to "fetchFromCache" because we are fetching from previously cached data?

Comment (fritzduchardt) [reply pkg/vendir/directory/directory.go:89]: Hi @prembhaskal, I am open to renaming the flag, but it should not contain the word "cache", since we copy from the already fetched final content location and not a cache, i.e. a separate copy that is kept to increase performance. "Fetching" in this context means for me "to pull from the source location defined in the vendir.yml".

Comment (prembhaskal) [reply pkg/vendir/directory/directory.go:89]: hmm fine. I think for current review it is fine. But we can think of changing name as a refactoring PR.

**Comment by prembhaskal** [comment]
looks good for me. @joaopapereira  you can have a look at it when you get time.

**Review by joaopapereira — APPROVED** [review]
LGTM
