### PR TITLE
fix: close tmp file before rename

### LINKED ISSUE #359: Vendir sync with http on windows fails because of a missing close before rename
**What steps did you take:**

```shell
git clone git@github.com:carvel-dev/vendir.git
cd vendir
go run .\cmd\vendir\vendir.go sync --chdir .\examples\http\
```

**What happened:**

The example fails on windows (in powershell).

```shell
Fetching: vendor + k8s-simple-app-plain (http from https://dk-shared-assets.s3.amazonaws.com/k8s-simple-app-example-master.zip)
vendir: Error: Syncing directory 'vendor':
  Syncing directory 'k8s-simple-app-plain' with HTTP contents: rename .vendir-tmp-632954061\incoming\vendir-http2106031697 .vendir-tmp-632954061\incoming\k8s-simple-app-example-master.zip:
    The process cannot access the file because it is being used by another process.
exit status 1
```

**What did you expect:**

It should download the files.

**Anything else you would like to add:**

I have the same problem with the latest version of vendir but you can reproduce it using the examples and the current develop branch.

The cause is a missing call to `tmpFile.Close()` before an ` os.Rename(tmpFile.Name(), archivePath)` that is located here :
https://github.com/carvel-dev/vendir/blob/develop/pkg/vendir/fetch/http/sync.go#L51

You can fix it by closing the file first like this :

```go
archivePath := filepath.Join(incomingTmpPath, path.Base(t.opts.URL))
tmpFile.Close() // add this line
err = os.Rename(tmpFile.Name(), archivePath)
```

**Environment:**

- vendir version (execute `vendir --version`): current develop branch & latest release
- OS (e.g. from `/etc/os-release`): windows

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by meier-christoph**
This should fix #359

### CODE REVIEW

**Comment by kumaritanushree** [comment]
LGTM

File: pkg/vendir/fetch/http/sync.go [hunk 1]
```diff
@@ -48,6 +48,7 @@ func (t *Sync) Sync(dstPath string, tempArea ctlfetch.TempArea) (ctlconf.LockDir
 
 	incomingTmpPath := filepath.Dir(tmpFile.Name())
 	archivePath := filepath.Join(incomingTmpPath, path.Base(t.opts.URL))
+	tmpFile.Close()
```
Comment (joaopapereira) [inline pkg/vendir/fetch/http/sync.go:51]: Since we are actively closing the file here, can we remove the defer from line 41 and copy this line to the if statement in line 45?

This way, we will not try to close the same file twice.

Comment (meier-christoph) [reply pkg/vendir/fetch/http/sync.go:51]: true, I made the change

**Review by joaopapereira — APPROVED** [review]
LGTM
