### PR TITLE
Check on existence of unpackArchive path 

### LINKED ISSUE #184: clearer error message if path for githubrelease archive does not exist
**What steps did you take:**
I tried to unpack a github release with the wrong archive name. Here is a vendir.yaml file to replicate:
```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  # unpacks archive included in the release
  - path: github.com/cloudfoundry-incubator/eirini-release
    githubRelease:
      slug: cloudfoundry-incubator/eirini-release
      tag: v1.2.0
      checksums:
        eirini-cf.tgz: 819b37126f81ad479acc8dcd7e61e8b0e55153d8fa27aa9a04692c38d0c310fe
        eirini-uaa.tgz: efe8a498c67368fac1c46fa52c484261cbf4e78b3291cff69e660cd863342674
        eirini.tgz: b535d9434300e79d11d42acc417148d09054aa32808dab5f12264d3af59ad548
      unpackArchive:
        path: thisfiledoesnotexist.tgz
```

**What happened:**
You get the error:
> vendir: Error: Syncing directory 'vendor':
  Syncing directory 'github.com/cloudfoundry-incubator/eirini-release' with github release contents:
    Expected known archive type (zip, tgz, tar)

**What did you expect:**
An error message which tells me that the specified file does not exist. Can be implemented by a check before trying to unpack it.

**Environment:**

- vendir version: 0.31.0
- OS: Debian Bookworm

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by kumaritanushree**
Added check on existence of `unpackArchive` path and throw detailed error if path does not found.
Fixes  #184

### CODE REVIEW

File: pkg/vendir/fetch/githubrelease/sync.go [hunk 1]
```diff
@@ -175,6 +175,11 @@ func (d Sync) Sync(dstPath string, tempArea ctlfetch.TempArea) (ctlconf.LockDire
 
 		defer os.RemoveAll(newIncomingTmpPath)
 
+		_, err = os.Stat(filepath.Join(incomingTmpPath, d.opts.UnpackArchive.Path))
+		if err != nil {
+			return lockConf, err
```
Comment (joaopapereira) [inline pkg/vendir/fetch/githubrelease/sync.go:183]: I think we should be a little bit more explicit on the error message. If it is PathNotFound we should let people know that the file they want to unpack is not part of the github release

**Review by joaopapereira — CHANGES_REQUESTED** [review]
I added a comment about the error message.
Also, do you think adding some tests around this behavior is possible?

File: pkg/vendir/fetch/githubrelease/sync.go (hunk 1 above)
Comment (kumaritanushree) [reply pkg/vendir/fetch/githubrelease/sync.go:183]: Updated error with more information and added e2e test as well.

File: test/e2e/github_release_test.go [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+        path: eirini.tgz
+`
+
+	expectedErr := `vendir: Error: Syncing directory 'vendor':
+  Syncing directory 'github.com/cloudfoundry-incubator/eirini-release' with github release contents:
+    Unpacking archive 'thisfiledoesnotexist.tgz' is not part of the github release
+`
+
+	logger.Section("sync with mismatch github release path", func() {
+		_, err := vendir.RunWithOpts([]string{"sync", "-f", "-"}, RunOpts{StdinReader: strings.NewReader(yaml), AllowError: true})
```
Comment (joaopapereira) [inline test/e2e/github_release_test.go]: I think we should use a temporary directory to run these tests on. If not we will be polluting the folder where the test file is present

**Review by joaopapereira — CHANGES_REQUESTED** [review]
The implementation looks good, please just ensure you are using a temp directory to store the results of the test

File: test/e2e/github_release_test.go [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+
+func TestGithubRelease(t *testing.T) {
+	env := BuildEnv(t)
+	logger := Logger{}
+	vendir := Vendir{t, env.BinaryPath, logger}
+
+	dstPath, err := os.MkdirTemp("", "vendir-e2e-github-release-dst")
+	if err != nil {
+		t.Fatal(err)
+	}
```
Comment (joaopapereira) [inline test/e2e/github_release_test.go]:
```suggestion
	require.NoError(t, err)
```

This change is just to keep the pattern we are using consistent

File: test/e2e/github_release_test.go [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+// SPDX-License-Identifier: Apache-2.0
+
+package e2e
+
+import (
+	"os"
+	"strings"
+	"testing"
+
+	"github.com/stretchr/testify/assert"
```
Comment (joaopapereira) [inline test/e2e/github_release_test.go:11]:
```suggestion
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
```

File: test/e2e/github_release_test.go [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+`
+
+	expectedErr := `vendir: Error: Syncing directory 'vendor':
+  Syncing directory 'github.com/cloudfoundry-incubator/eirini-release' with github release contents:
+    Unpacking archive 'thisfiledoesnotexist.tgz' is not part of the github release
+`
+
+	logger.Section("sync with mismatch github release path", func() {
+		_, err := vendir.RunWithOpts([]string{"sync", "-f", "-"}, RunOpts{Dir: dstPath, StdinReader: strings.NewReader(yaml), AllowError: true})
+		assert.Error(t, err, "Expected to err while syncing with github release")
```
Comment (joaopapereira) [inline test/e2e/github_release_test.go]:
```suggestion
		require.Error(t, err, "Expected to err while syncing with github release")
```

File: test/e2e/github_release_test.go [hunk 6]
```diff
@@ -0,0 +1,77 @@
...
+		assert.ErrorContains(t, err, expectedErr)
+	})
+
+	logger.Section("sync again with github release", func() {
+		_, err := vendir.RunWithOpts([]string{"sync", "-f", "-"}, RunOpts{Dir: dstPath, StdinReader: strings.NewReader(yaml1)})
+		assert.NoError(t, err)
```
Comment (joaopapereira) [inline test/e2e/github_release_test.go]:
```suggestion
		require.NoError(t, err)
```

**Review by joaopapereira — CHANGES_REQUESTED** [review]
A couple of comments.

When you use the assert package in testify even if the assertion fails the test continues and in cases where we want to check for error we should always use require because if the assertion fails the test will stop. Usually, there is no good reason to continue a test when we are checking for the existence or absence of an error and that assertion fails.

**Review by joaopapereira — APPROVED** [review]
LGTM

**Review by cppforlife — APPROVED** [review]
