### PR TITLE
fix: support tar and tgz archives containing symbolic links

### LINKED ISSUE #395: GitHubRelease Unpack Archive Cannot Unpack Archives with Symlinks
**What steps did you take:**
Attempt to sync the following `vendir.yml`
```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: .
    githubRelease:
      slug: ollama/ollama
      latest: true
      disableAutoChecksumValidation: true
      assetNames:
      - ollama-linux-amd64.tgz
      unpackArchive:
        path: ollama-linux-amd64.tgz
```

**What happened:**
```
➜  vendir sync                                                                                 
Fetching: vendor + . (github release ollama/ollama@latest)

vendir: Error: Syncing directory 'vendor':
  Syncing directory '.' with github release contents:
    Expected known archive type (zip, tgz, tar)
```

**What did you expect:**
I expected the tarball to be expanded to the vendor directory.

**Anything else you would like to add:**
It's almost certainly because [this code](https://github.com/carvel-dev/vendir/blob/develop/pkg/vendir/fetch/archive.go#L147-L163) doesn't know what a symlink is.  The same problem probably exists in Zip files.

**Environment:**

- vendir version (execute `vendir --version`): `vendir version 0.41.0`
- OS (e.g. from `/etc/os-release`): Darwin

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by DocX**
## description

adds support for symlink tar entry to extract as symlink

added archive unit tests with synthetic archive files generation

Fixes https://github.com/carvel-dev/vendir/issues/395

## symbolic links checks

symbolic links still are verified after the unarchiving in the other parts of the sync, so supporting symlinks should not create new security issue.

Created test release here with some test archives: https://github.com/DocX/vendir/releases/tag/test-release

### Symbolic link to other file in archive:

```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      # unpacks archive that contains symlinks
      - path: github.com/docx/vendir/test-symlink
        githubRelease:
          slug: docx/vendir
          tag: test-release
          checksums:
            test-archive.tar.gz: 7ddbd22239c359e79d2788261d0802b6926005b6540cd52204c89a1084798128
            test-archive-invalid-symlink.tar.gz: 9997b306d6352dd33f239e38c00db8b3d2f9ade291116c047e973c39cff9d524
            test-archive-external-symlink.tar.gz: 0982e0328e1d5a08d3d56941d5b3bd1c30e4abb318d9895da3d9d6117b6960de
          unpackArchive:
            path: test-archive.tar.gz
```

Output
```
$ vendir sync
Fetching: vendor + github.com/docx/vendir/test-symlink (github release docx/vendir@test-release)

$ ls -laR vendor
vendor/github.com/docx/vendir/test-symlink/test-archive:
total 24
drwx------  6 lukasdolezal  staff  192 Feb  4 12:11 .
drwx------  3 lukasdolezal  staff   96 Feb  4 12:11 ..
-rw-r--r--  1 lukasdolezal  staff   28 Feb  4 12:11 file1.txt
-rw-r--r--  1 lukasdolezal  staff   29 Feb  4 12:11 file2.txt
-rw-r--r--  1 lukasdolezal  staff   28 Feb  4 12:11 file3.txt
lrwxr-xr-x  1 lukasdolezal  staff    9 Feb  4 12:11 link-to-file1.txt -> file1.txt
```

### Symbolic link to non existing file outside the archive:
```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      # fails to unpacks archive that contains symlinks that point outside of archive (not existing)
      - path: github.com/docx/vendir/test-invalid-symlink
        githubRelease:
          slug: docx/vendir
          tag: test-release
          checksums:
            test-archive.tar.gz: 7ddbd22239c359e79d2788261d0802b6926005b6540cd52204c89a1084798128
            test-archive-invalid-symlink.tar.gz: 9997b306d6352dd33f239e38c00db8b3d2f9ade291116c047e973c39cff9d524
            test-archive-external-symlink.tar.gz: 0982e0328e1d5a08d3d56941d5b3bd1c30e4abb318d9895da3d9d6117b6960de
          unpackArchive:
            path: test-archive-invalid-symlink.tar.gz
```

Output
```
$ vendir sync
Fetching: vendor + github.com/docx/vendir/test-invalid-symlink (github release docx/vendir@test-release)

vendir: Error: Unable to resolve symlink: lstat /private/tmp/external-file.txt: no such file or directory

$ ls -laR vendor
vendor/github.com/docx/vendir/test-invalid-symlink/test-archive-invalid:
total 16
drwx------  5 lukasdolezal  staff  160 Feb  4 12:11 .
drwx------  3 lukasdolezal  staff   96 Feb  4 12:11 ..
lrwxr-xr-x  1 lukasdolezal  staff   22 Feb  4 12:11 external-link.txt -> /tmp/external-file.txt
-rw-r--r--  1 lukasdolezal  staff   20 Feb  4 12:11 file1.txt
-rw-r--r--  1 lukasdolezal  staff   18 Feb  4 12:11 file2.txt
```

### Symbolic link to external system file (`/etc/hosts`)
```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      # fails to unpacks archive that contains symlinks that point outside of archive (/etc/hosts)
      - path: github.com/docx/vendir/test-external-symlink
        githubRelease:
          slug: docx/vendir
          tag: test-release
          checksums:
            test-archive.tar.gz: 7ddbd22239c359e79d2788261d0802b6926005b6540cd52204c89a1084798128
            test-archive-invalid-symlink.tar.gz: 9997b306d6352dd33f239e38c00db8b3d2f9ade291116c047e973c39cff9d524
            test-archive-external-symlink.tar.gz: 0982e0328e1d5a08d3d56941d5b3bd1c30e4abb318d9895da3d9d6117b6960de
          unpackArchive:
            path: test-archive-external-symlink.tar.gz
```

Output:
```
$ vendir sync
Fetching: vendor + github.com/docx/vendir/test-external-symlink (github release docx/vendir@test-release)

vendir: Error: Invalid symlink found to outside parent directory: "/private/etc/hosts"

$ ls -laR vendor
vendor/github.com/docx/vendir/test-external-symlink:
total 24
drwx------  6 lukasdolezal  staff  192 Feb  4 12:17 .
drwx------  3 lukasdolezal  staff   96 Feb  4 12:17 ..
lrwxr-xr-x  1 lukasdolezal  staff   10 Feb  4 12:17 external-symlink -> /etc/hosts
-rw-r--r--  1 lukasdolezal  staff   20 Feb  4 12:17 file1.txt
-rw-r--r--  1 lukasdolezal  staff   20 Feb  4 12:17 file2.txt
-rw-r--r--  1 lukasdolezal  staff   20 Feb  4 12:17 file3.txt
```

### CODE REVIEW

File: pkg/vendir/fetch/archive.go [hunk 1]
```diff
@@ -158,14 +158,36 @@ func (t Archive) tryTarWithGzip(path, dstPath string, gzipped bool) (bool, error
...
 
+		case tar.TypeSymlink:
+			err = t.createSymlink(dstPath, header.Name, header.Linkname)
+			if err != nil {
+				return true, err
+			}
+
 		default:
-			return false, fmt.Errorf("Unknown file '%s' (%d)", header.Name, header.Typeflag)
+			return true, fmt.Errorf("Unsupported file type '%s' (%d)", header.Name, header.Typeflag)
```
Comment (DocX) [inline pkg/vendir/fetch/archive.go]: Provide better error message by returning `true` indicating this is already the "final" file format. In this case the file is already known to be tar/targz

File: pkg/vendir/fetch/archive.go [hunk 2]
```diff
@@ -158,14 +158,36 @@ func (t Archive) tryTarWithGzip(path, dstPath string, gzipped bool) (bool, error
...
 		}
 	}
 
 	return true, nil
 }
 
+func (t Archive) createSymlink(dstPath, symlinkPath, targetPath string) error {
```
Comment (joaopapereira) [inline pkg/vendir/fetch/archive.go]: I believe that this might be covered by the main loop but can you check if you download an archive that has symlinks to outside of the current folder to make sure it fails?

**Review by joaopapereira — CHANGES_REQUESTED** [review]
Keeping this as request changes until we have an answer to the question in the comments.

The PR looks good, not sure if we should have a test at integration level to make sure that the symlink check is working in this case.

In terms of the linter we were discussing possible relaxing some of the constraints but did not go around doing it.

I think that the majority of them can be ignore, like the magic numbers for permission and complexity in tests

File: pkg/vendir/fetch/archive.go (hunk 2 above)
Comment (DocX) [reply pkg/vendir/fetch/archive.go]: Tested it manually, see the updated PR summary.

**Review by joaopapereira — APPROVED** [review]
LGTM
