### PR TITLE
Fix #423

### LINKED ISSUE #423: vendir sync fails syncing helm chart for bitnami (and potentially others)
**What steps did you take:**

1. create the following `vendir.yml`:

   ```yaml
   apiVersion: vendir.k14s.io/v1alpha1
   kind: Config
   directories:
     - path: vendor
       contents:
         - path: external-dns
           helmChart:
             name: external-dns
             version: 9.0.0
             repository:
               url: https://charts.bitnami.com/bitnami
           helmVersion: 3
   ```
2. run `vendir sync`

**What happened:**

Sync failed with the following error:

```
Fetching: vendor + external-dns (helm chart from https://charts.bitnami.com/bitnami@external-dns:9.0.0)

vendir: Error: Syncing directory 'vendor':
  Syncing directory 'external-dns' with helm chart contents:
    Finding single helm chart:
      Expected single directory in charts directory, but was: [external-dns external-dns:9.0.0]
```

**What did you expect:**
I expected the sync to succeed

**Anything else you would like to add:**

The problem involves this block of code here:

https://github.com/carvel-dev/vendir/blob/develop/pkg/vendir/fetch/helmchart/sync.go#L127-L132

- the directory being evaluated is populated by running `helm fetch <chart-name> --untar --untardir <chartsPath> --repo https://charts.bitnami.com/bitnami` 
- the result of this command is not consistent across chart providers
- bitnami, for example, does not have a *.tgz extension, so the filter in the above snippet does not catch it
- the result is that the sanity check fails, causing vendir to exit with an error

You can see what I mean by running the following commands:

```
helm fetch aws-ebs-csi-driver --untar --untardir ./kubernetes-sigs --repo https://kubernetes-sigs.github.io/aws-ebs-csi-driver
helm fetch external-dns --untar --untardir ./bitnami --repo https://charts.bitnami.com/bitnami
ls bitnami/
ls kubernetes-sigs/
```

output:
```
➜  vendir ls bitnami
external-dns       external-dns:9.0.2
cluster: seceng_dev_usgw1/seceng-dev-us-gov-west-1
➜  vendir ls kubernetes-sigs
aws-ebs-csi-driver            aws-ebs-csi-driver-2.47.0.tgz
```

**Environment:**

- vendir version (execute `vendir --version`): 0.44.0
- OS (e.g. from `/etc/os-release`): macos
- helm version: 3.18.4 (latest as of this writing)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by gblues**
== DETAILS

My proposed solution for this bug is, instead of relying on naming convention, we instead collect a list of subdirectories that contain `Chart.yaml`.

Credit to https://stackoverflow.com/a/12518877 for the idiomatic "check if file exists" example.

### CODE REVIEW

**Comment by gblues** [comment]
@Zebradil @joaopapereira

File: pkg/vendir/fetch/helmchart/sync.go [hunk 1]
```diff
@@ -126,7 +126,8 @@ func (t *Sync) findChartDir(chartsPath string) (string, error) {
 
 	var dirNames []string
 	for _, file := range files {
-		if file.IsDir() && !strings.HasSuffix(file.Name(), ".tgz") {
+		// #423 - instead of relying on a naming convention, collect paths that contain a Chart.yaml
```
Comment (praveenrewar) [inline pkg/vendir/fetch/helmchart/sync.go]: nit: remove comment
```suggestion
```

**Review by praveenrewar — COMMENTED** [review]
Thank you for the PR @gblues! 
The changes look good, I am just a bit surprised that the tests didn't run, could you push another commit and see if they run now.

**Review by Zebradil — APPROVED** [review]
I second removing the comment, otherwise LGTM.

**Comment by gblues** [comment]
@praveenrewarI have updated the PR as requested. Github reports there are "3 workflows awaiting approval" which @praveenrewar is likely the tests you were interested in before.

@Zebradil it doesn't look like your approval was sufficient because you don't have write access. who's got write access?

**Comment by Zebradil** [comment]
Yes, as an external contributor I have limited permissions here.

BTW, the lint job failed. Golangci-lint wants lines to be 80 characters long at most. I'm not sure whether this is a hard required from the maintainers or not. Maybe it makes sense to relax the rule.

**Comment by joaopapereira** [comment]
There are some linting issues when they are fixed I think we can get this merged

**Comment by gblues** [comment]
@joaopapereira linter issue should be resolved, the CI builds will need to be re-approved

**Review by joaopapereira — APPROVED** [review]
LGTM

**Comment by reegnz** [comment]
@joaopapereira Can we have a release with this?
