### PR TITLE
fix fetching a helm chart via oci

### LINKED ISSUE #144: helmChart fetch broken for OCI source repositories
This is a duplicate tracking issue for https://github.com/vmware-tanzu/carvel-kapp-controller/issues/588

### PR DESCRIPTION
**Pull request by DennisDenuto**
Fixes: https://github.com/vmware-tanzu/carvel-vendir/issues/144

Note:
- this PR is based off https://github.com/vmware-tanzu/carvel-vendir/pull/166

### CODE REVIEW

File: test/e2e/example.go [hunk 1]
```diff
@@ -4,16 +4,20 @@
...
 type example struct {
-	Name       string
-	Env        []string
-	OnlyLocked bool
-	SkipRemove bool
+	Name              string
+	Env               []string
+	OnlyLocked        bool
+	SkipRemove        bool
+	YttVendirYamlArgs []string
```
Comment (cppforlife) [inline test/e2e/example.go]: neat! though for the sake of minimizing dependencies, should we just do string replace (e.g. vendir.yml can have REPLACE_ME_REGISTRY_ADDR)?

Comment (DennisDenuto) [reply test/e2e/example.go]: ok fine.... sounds reasonable!

Comment (DennisDenuto) [reply test/e2e/example.go]: ok done
